# Generated by Django 5.2.2 on 2026-05-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('g', 'Gramas'), ('ml', 'Mililitros'), ('un', 'Unidade')], max_length=2)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_insumo', to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaDiretaAoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True)),
                ('produto_final', models.OneToOneField(limit_choices_to={'is_composicao': True}, on_delete=django.db.models.deletion.CASCADE, related_name='receita', to='core.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=8)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_receitas', to='core.produto')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cafeteria.receitadiretaaocliente')),
            ],
        ),
    ]
