# Generated by Django 5.2.2 on 2026-05-04 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papelaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='papelaria', to='core.produto')),
            ],
        ),
    ]
