# Generated by Django 5.2.2 on 2026-05-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tipo', models.CharField(choices=[('livro', 'Livraria'), ('papelaria', 'Papelaria'), ('cafe_insumo', 'Insumo de Café'), ('cafe_receita', 'Receita de Café'), ('cafe_direto', 'Venda Direta de Café')], max_length=20)),
                ('is_composicao', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
